config/routes.rb
Rails.application.routes.draw do
  resources :pledges, except: [:index, :delete]
  resources :projects, except: [:edit, :update, :delete]
  resources :users, except: [:delete]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pledge.rb
class Pledge < ApplicationRecord
    belongs_to :user
    belongs_to :project 

    validates(:amount, {presence: true, numericality: true})
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :pledges
    has_many :users, through: :pledges

end

app/models/user.rb
class User < ApplicationRecord
    has_many :pledges
    has_many :projects, through: :pledges
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController

    def new
        @pledge = Pledge.new
    end

    def show
        @projects = Project.all
        @pledge = Pledge.find(params[:id])
    end

    # def create
    #     @project = Project.find_by(id: params[:pledge][:project_id])
    #     @pledge = Pledge.create(pledge_params)
    #     redirect_to project_path(@project)
    # end

    def create
        @project = Project.find_by(id: params[:pledge][:project_id])
        @pledge = Pledge.new(pledge_params)
        if @pledge.valid?
            @pledge.save
            redirect_to project_path(@project)
        else
            flash[:errors] = @pledge.errors.full_messages
            redirect_to new_pledge_path
        end
    end


    private

    def pledge_params
        params.require(:pledge).permit(:amount, :user_id, :project_id)
    end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

    def index
        @projects = Project.all
    end

    def show
        find_project
    end

    def new
        @project = Project.new
    end

    def create
        @project = Project.new(project_params)
        @project.save
        redirect_to project_path(@project)
    end

    private

    def find_project
        @project = Project.find(params[:id])
    end

    def project_params
        params.require(:project).permit(:name, :goal, :amount)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.all
    end

    def show
        find_user
    end

    def new
        @user = User.new
    end

    def edit
        find_user
    end

    def create
        @user = User.create(user_params)
        redirect_to user_path(@user)
    end

    def update
        @user = find_user
        @user.update(user_params)
        redirect_to user_path(@user)
    end

    private

    def find_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pledge_helper.rb
module PledgeHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kickflip</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pledges/new.html.erb
<% if flash[:errors] %>
    <% flash[:errors].each do |e| %>
        <p> <%= e %></p>
    <% end %>
<% end %>


<%= form_with model: @pledge do |f| %>
    <%= f.collection_select(:user_id, User.all, :id, :name) %>
    <%= f.collection_select(:project_id, Project.all, :id, :name) %>
    <%= f.text_field :amount, placeholder: "amount" %>
    <%= f.submit %>
<% end %>

<p><%= link_to "Back to Projects Index", projects_path %></p>

app/views/pledges/show.html.erb
<h1> Your Pledges</h1>

<% @projects.each do |project| %>
    <%= project.pledges.count %>
    
<% end %>

app/views/projects/_form.html.erb
<%= form_with model: @project do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :goal %><br>
    <%= form.text_field :goal %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/projects/index.html.erb
<h1>Projects Index</h1>

<% @projects.each do |project| %>
    <p> <%= link_to project.name, project_path(project)  %> </p>
<% end %>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>Create a new Project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>
<h2> Project Goal: $ <%= @project.goal %></h2>
<h2> Current Pledges: <%= @project.pledges.count %>  </h2>
<h3> Current Pledge Amount: </h3>
<% sum = 0 %>
<% @project.pledges.each do |pledge| %></h2>
    <% sum += pledge.amount%>
<% end %>
<h3> $ <%= sum %> </h3>

<h3>Project Backers:</h3>
<% @project.users.uniq.each do |user| %>
    <p> <%= link_to user.name, user_path(user) %></p>
<% end %>

<p> <strong><%= link_to "Back this Project", new_pledge_path %> </strong></p>
<p><strong><%= link_to 'Back to Index', projects_path %> </strong></p>

app/views/users/_form.html.erb
<%= form_with model: @user do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>

<%= render 'form' %>
<%= link_to "Back", user_path %>

app/views/users/index.html.erb
<h1>User Index</h1>

<% @users.each do |user| %>
    <h2><%= link_to user.name, user_path(user) %></h2>
<% end %>

<p> <%= link_to "Create New User", new_user_path %></p>

app/views/users/new.html.erb
<h1>Create a New User Profile:</h1>
<%= form_with model: @user do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/users/show.html.erb
<h1> <%= @user.name %></h1>

<% @user.projects.uniq.each do |project| %>
    <p><%= link_to project.name, project_path(project) %></p>
<% end %>

<p><%= link_to "Back", users_path %> </p>
<p><%= link_to "Edit this User", edit_user_path %> </p>